stages:
  - infra-apply
  - build
  - deploy

Terraform Apply:
  stage: infra-apply
  only:
    - main
  image: hashicorp/terraform:latest #i_too_like_to_live_dangerously.gif
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - terraform apply --auto-approve
  dependencies: [ ]

React Build:
  stage: build
  only:
    - main
  image: node:17
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - 'build/'
    expire_in: 1 day
  dependencies:
    - Terraform Apply

Deploy Site:
  stage: deploy
  only:
    - main
  image: amazon/aws-cli
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - aws s3 sync build s3://alloba-personal-landing-site-default --delete
  dependencies:
    - React Build