stages:
  - infra-apply
  - build
  - deploy

Terraform Apply:
  stage: infra-apply
  only:
    - main
  image:
    name: hashicorp/terraform:latest #i_too_like_to_live_dangerously.gif
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
  before_script:
    - cd terraform
  script:
    - terraform init
    - terraform apply --auto-approve
  dependencies: [ ]

React Build:
  stage: build
  only:
    - main
  image: node:17
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - 'build/'
    expire_in: 1 day
  dependencies:
    - Terraform Apply

Deploy Site:
  stage: deploy
  only:
    - main
  image:
    name: amazon/aws-cli
    entrypoint: [""] # aws cli expects you to run commands inline. so overriding entry point for to not break.
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - aws s3 sync build s3://alexlbates.com --delete
  dependencies:
    - React Build
