baseURL = 'https://alexlbates.com'
languageCode = 'en-us'
title = 'Alex Bates'
theme = "terminal"

[params]
    # dir name of your main content (default is `content/posts`).
    # the list of set content will show up on your index page (baseurl).
    contentTypeName = "posts"

    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "red"

    # the number of items to show in the top menu of the site
    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 4

    # show selector to switch language
    showLanguageSelector = false

    # set theme to full screen width
    fullWidthTheme = false

    # center theme with default width
    centerTheme = true

    # set post to show the last updated
    # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
    showLastUpdated = true
    enableGitInfo = true



[languages]
    [languages.en]
    summaryLength = 5 # How many words are used for page summaries (ish, there is an effort to match to nearest sentence)
        [languages.en.params.logo]
            logoText = "AB"
            logoHomeLink = "/"
        [[languages.en.menu.main]]
            identifier = "projects"
            name = "Projects"
            url = "/projects"
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About"
            url = "/about"
        [[languages.en.menu.main]]
            identifier = "tech-notes"
            name = "Tech Notes"
            url = "/tech-notes"

