name: Deploy to Remote
on:
  - workflow_dispatch
#  push:
#    branches: [main]


jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Directory
        run: cd terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Apply Terraform
        run: terraform apply --auto-approve

#  SiteBuild:
#    klakegg/hugo:latest
#  Deploy:
