name: Deploy to Remote
on:
  - workflow_dispatch
  - push
#  push:
#    branches: [main]


jobs:
  TerraformApply:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
#    container: hashicorp/terraform:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd terraform 
          terraform apply --auto-approve

#  SiteBuild:
#    klakegg/hugo:latest
#  Deploy:
